services:
  apps:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: node-app 
    ports: 
      - "3000:3000"
    environment: 
      - NODE_ENV=PRODUCTION
    networks:
      - app-network

  nginx:
    image: nginx:latest 
    container_name: nginx-container 
    ports:
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks: 
       - app-network
    depends_on: 
      - app

networks:
  app-network:
    driver: bridge 

